# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
es:
  languageCode: es
  #Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/es

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en-us
  contentDir: content/en
  title: Filocomplex (in English!)
  params:
    description: Nothing to see here yet.
  menu:
    main:
#      - name: 传
#        url: '#about'
#        weight: 1
